<?php
/**
 * @file
 */

/**
 * Implements hook_permission().
 */
function css_field_permission() {
  return array(
    'view css field debug' => array(
      'title' => t('View CSS field debug'),
      'description' => t('When debug enabled for a css field, messaging will display for user.'),
    ),
  );
}

/**
 * Implements hook_field_info().
 */
function css_field_field_info() {
  return array(
    // CSS snippet field information
    'css_field' => array(
      'label' => t("CSS"),
      'description' => t("This field stores CSS and media information in the database."),
      'default_widget' => 'css_field',
      'default_formatter' => 'css_field',
    ),
    // CSS file field information
    'css_file' => array(
      'label' => t("CSS file"),
      'description' => t("This field stores a CSS file and media/description information."),
      'settings' => array(
        'uri_scheme' => variable_get('file_default_scheme', 'public'),
      ),
      'instance_settings' => array(
        'file_directory' => 'css-files',
        'max_filesize' => '',
        'description_field' => 0,
      ),
      'default_widget' => 'css_file',
      'default_formatter' => 'css_file',
    ),
  );
}

/**
 * Implements hook_field_settings_form().
 */
function css_field_field_settings_form($field, $instance, $has_data) {
  $type = $field['type'];
  $defaults = field_info_field_settings($field['type']);
  $settings = array_merge($defaults, $field['settings']);

  $form = array();

  if ($type == 'css_file') {
    $scheme_options = array();
    foreach (file_get_stream_wrappers(STREAM_WRAPPERS_WRITE_VISIBLE) as $scheme => $stream_wrapper) {
      $scheme_options[$scheme] = $stream_wrapper['name'];
    }
    $form['uri_scheme'] = array(
      '#type' => 'radios',
      '#title' => t('Upload destination'),
      '#options' => $scheme_options,
      '#default_value' => $settings['uri_scheme'],
      '#description' => t('Select where the final files should be stored. Private file storage has significantly more overhead than public files, but allows restricted access to files within this field.'),
      '#disabled' => $has_data,
    );
  }

  return $form;
}

/**
 * Implements hook_field_instance_settings_form().
 */
function css_field_field_instance_settings_form($field, $instance) {
  $type = $field['type'];
  $settings = $instance['settings'];

  $form = array();

  if ($type == 'css_file') {
    $form['file_directory'] = array(
      '#type' => 'textfield',
      '#title' => t('File directory'),
      '#default_value' => $settings['file_directory'],
      '#description' => t('Optional subdirectory within the upload destination where files will be stored. Do not include preceding or trailing slashes.'),
      '#element_validate' => array('_file_generic_settings_file_directory_validate'),
      '#weight' => 3,
    );

    $form['max_filesize'] = array(
      '#type' => 'textfield',
      '#title' => t('Maximum upload size'),
      '#default_value' => $settings['max_filesize'],
      '#description' => t('Enter a value like "512" (bytes), "80 KB" (kilobytes) or "50 MB" (megabytes) in order to restrict the allowed file size. If left empty the file sizes will be limited only by PHP\'s maximum post and file upload sizes (current limit <strong>%limit</strong>).', array('%limit' => format_size(file_upload_max_size()))),
      '#size' => 10,
      '#element_validate' => array('_file_generic_settings_max_filesize'),
      '#weight' => 5,
    );

    $form['description_field'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable <em>Description</em> field'),
      '#default_value' => isset($settings['description_field']) ? $settings['description_field'] : '',
      '#description' => t('The description field allows users to enter a description about the uploaded file.'),
      '#parents' => array('instance', 'settings', 'description_field'),
      '#weight' => 11,
    );
  }

  return $form;
}

/**
 * Implements hook_field_widget_info().
 */
function css_field_field_widget_info() {
  return array(
    // CSS Snippet widget information
    'css_field' => array(
      'label' => t('CSS snippet'),
      'field types' => array('css_field'),
      'settings' => array(
        'css_field_editor_theme' => 'solarized_dark',
        'css_field_enable_online_validation' => FALSE,
      ),
      'weight' => 0,
    ),
    // CSS file widget information
    'css_file' => array(
      'label' => t('CSS file'),
      'field types' => array('css_file'),
      'settings' => array(
        'progress_indicator' => 'throbber',
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_CUSTOM,
        'default value' => FIELD_BEHAVIOR_NONE,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function css_field_field_widget_settings_form($field, $instance) {
  $type = $field['type'];
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  $element = array();

  if ($type == 'css_field') {
    $element['css_field_editor_theme'] = array(
      '#type' => 'select',
      '#options' => _css_field_list_of_editor_themes(),
      '#title' => t('Select editor theme'),
      '#description' => t("Select the editor's theme style for the css field"),
      '#default_value' => isset($settings['css_field_editor_theme']) ? $settings['css_field_editor_theme'] : 'solarized_dark',
    );

    $element['css_field_enable_online_validation'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable W3Validation'),
      '#description' => t('This will enable a remote validation service to scan the css and report errors with the css before allowing it to be saved.'),
      '#default_value' => isset($settings['css_field_enable_online_validation']) ? $settings['css_field_enable_online_validation'] : FALSE,
    );
  }

  if ($type == 'css_file') {
    $form['progress_indicator'] = array(
      '#type' => 'radios',
      '#title' => t('Progress indicator'),
      '#options' => array(
        'throbber' => t('Throbber'),
        'bar' => t('Bar with progress meter'),
      ),
      '#default_value' => $settings['progress_indicator'],
      '#description' => t('The throbber display does not show the status of uploads but takes up less space. The progress bar is helpful for monitoring progress on large uploads.'),
      '#weight' => 16,
      '#access' => file_progress_implementation(),
    );
  }

  return $element;
}

/**
 * Implements hook_field_widget_form().
 */
function css_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $type = $field['type'];
  $widget = $instance['widget'];
  $settings = $widget['settings'];

  // For the CSS textarea/snippet field, the entire widget form is completely
  // built here in this function, unlike the CSS file widget.
  if ($type == 'css_field') {
    // Defaults
    $defaults = array(
      'css' => '',
      'media' => 'all',
      'description' => '',
    );

    // Bring in the javascript that sets the ace editor and sets the editor theme.
    if (isset($settings['css_field_editor_theme'])) {
      $editor_theme = $settings['css_field_editor_theme'];
      if ($editor_theme !== 'none') {
        drupal_add_js('//cdn.jsdelivr.net/ace/1.2.3/noconflict/ace.js', array('type' => 'external', 'scope' => 'header', 'group' => JS_THEME, 'every_page' => TRUE, 'weight' => -1,));
        drupal_add_js(drupal_get_path('module', 'css_field') . '/js/css_field.js');
      }
    }

    // If only one item, place it in a fieldset to keep it organized.
    if ($field['cardinality'] == 1) {
      $element['#type'] = 'fieldset';
    }

    // Items specific to snippet widget.
    $element['css'] = array(
      '#type' => 'textarea',
      '#title' => t('CSS snippet'),
      '#row' => 10,
      '#attributes' => array(
        'data-ace-editor-css' => 'data-ace-editor-css',
        'data-ace-editor-css-theme' => $editor_theme,
      ),
      '#default_value' => isset($items[$delta]['css']) ? check_plain($items[$delta]['css']) : $defaults['css'],
      '#description' => t('Do not add @media or &lt;style&gt; tags in your code.'),
    );

    // Basic html style tag media defaults.
    $options = array(
      'all' => t('All'),
      'screen' => t('Screen'),
      'print' => t('Print'),
      'speech' => t('Speech'),
    );

    // Integration with breakpoints. Add existing system breakpoints in with our
    // defaults from above.
    if (module_exists('breakpoints')) {
      $breakpoints = breakpoints_breakpoint_load_all();
      foreach ($breakpoints as $breakpoint) {
        $options[$breakpoint->machine_name] = $breakpoint->breakpoint;
      }
    }

    $element['media'] = array(
      '#type' => 'select',
      '#options' => $options,
      '#title' => t('Media query'),
      '#description' => t('Select what media (all, print, screen...) or breakpoint this css should be applied to.'),
      '#default_value' => isset($items[$delta]['media']) ? $items[$delta]['media'] : $defaults['media'],
    );
  }

  // The css file widget begins here, and includes construction from process and
  // value widget functions.
  if ($type == 'css_file') {
    $defaults = array(
      'fid' => 0,
      'media' => 'all',
      'description' => '',
    );

    // Load the items for form rebuilds from the field state as they might not be
    // in $form_state['values'] because of validation limitations. Also, they are
    // only passed in as $items when editing existing entities.
    $field_state = field_form_get_state($element['#field_parents'], $field['field_name'], $langcode, $form_state);
    if (isset($field_state['items'])) {
      $items = $field_state['items'];
    }

    // Essentially we use the managed_file type, extended with some enhancements.
    $element_info = element_info('managed_file');
    $element += array(
      '#type' => 'managed_file',
      '#upload_location' => file_field_widget_uri($field, $instance),
      '#upload_validators' => css_field_field_widget_upload_validators($field, $instance),
      '#value_callback' => 'css_field_field_widget_value',
      '#process' => array_merge($element_info['#process'], array('css_field_field_widget_process')),
      '#progress_indicator' => $settings['progress_indicator'],
      // Allows this field to return an array instead of a single value.
      '#extended' => TRUE,
    );

    if ($field['cardinality'] == 1) {

      // Set the default value.
      $element['#default_value'] = !empty($items) ? $items[0] : $defaults;

      // If there's only one field, return it as delta 0.
      if (empty($element['#default_value']['fid'])) {
        $element['#description'] = theme('file_upload_help', array('description' => $element['#description'], 'upload_validators' => $element['#upload_validators']));
      }

      $elements = array($element);
    }
    else {

      // If there are multiple values, add an element for each existing one.
      foreach ($items as $item) {
        $elements[$delta] = $element;
        $elements[$delta]['#default_value'] = $item;
        $elements[$delta]['#weight'] = $delta;
        $delta++;
      }

      // And then add one more empty row for new uploads except when this is a
      // programmed form as it is not necessary.
      if (($field['cardinality'] == FIELD_CARDINALITY_UNLIMITED || $delta < $field['cardinality']) && empty($form_state['programmed'])) {
        $elements[$delta] = $element;
        $elements[$delta]['#default_value'] = $defaults;
        $elements[$delta]['#weight'] = $delta;
        $elements[$delta]['#required'] = ($element['#required'] && $delta == 0);
      }

      // The group of elements all-together need some extra functionality
      // after building up the full list (like draggable table rows).
      $elements['#file_upload_delta'] = $delta;
      $elements['#theme'] = 'file_widget_multiple';
      $elements['#theme_wrappers'] = array('fieldset');
      $elements['#process'] = array('css_field_field_widget_process_multiple');
      $elements['#title'] = $element['#title'];
      $elements['#description'] = $element['#description'];
      $elements['#field_name'] = $element['#field_name'];
      $elements['#language'] = $element['#language'];
      $elements['#display_field'] = TRUE;

      // Add some properties that will eventually be added to the file upload
      // field. These are added here so that they may be referenced easily through
      // a hook_form_alter().
      $elements['#file_upload_title'] = t('Add a new file');
      $elements['#file_upload_description'] = theme('file_upload_help', array('description' => '', 'upload_validators' => $elements[0]['#upload_validators']));
    }

    return $elements;
  }

  return $element;
}

/**
 * The #value_callback for the file_generic field element.
 */
function css_field_field_widget_value($element, $input = FALSE, $form_state) {

  // We depend on the managed file element to handle uploads.
  $return = file_managed_file_value($element, $input, $form_state);

  // Ensure that all the required properties are returned even if empty.
  $return += array(
    'fid' => 0,
    'media' => 'all',
    'description' => '',
  );

  return $return;
}

/**
 * Retrieves the upload validators for a css file field.
 *
 * @param $field
 *   A field array.
 *
 * @return array
 *   An array suitable for passing to file_save_upload() or the file field
 *   element's '#upload_validators' property.
 */
function css_field_field_widget_upload_validators($field, $instance) {
  $validators = array();
  // Cap the upload size according to the PHP limit.
  $max_filesize = parse_size(file_upload_max_size());
  if (!empty($instance['settings']['max_filesize']) && parse_size($instance['settings']['max_filesize']) < $max_filesize) {
    $max_filesize = parse_size($instance['settings']['max_filesize']);
  }
  // There is always a file size limit due to the PHP server limit.
  $validators['file_validate_size'] = array($max_filesize);
  // Limit extensions to only '*.css' files.
  $validators['file_validate_extensions'] = array('css');

  return $validators;
}
/**
 * An element #process callback for the file_generic field type.
 *
 * Expands the file_generic type to include the description and display fields.
 */
function css_field_field_widget_process($element, &$form_state, $form) {
  $item = $element['#value'];
  $item['fid'] = $element['fid']['#value'];

  $field = field_widget_field($element, $form_state);
  $instance = field_widget_instance($element, $form_state);

  $defaults = array(
    'fid' => 0,
    'media' => 'all',
    'description' => '',
  );

  $element['#theme'] = 'file_widget';

  if ($item['fid']) {

    // Basic html style tag media defaults for the media selector.
    $options = array(
      'all' => t('All'),
      'screen' => t('Screen'),
      'print' => t('Print'),
      'speech' => t('Speech'),
    );

    // Integration with breakpoints. Add existing system breakpoints in with our
    // defaults from above.
    if (module_exists('breakpoints')) {
      $breakpoints = breakpoints_breakpoint_load_all();
      foreach ($breakpoints as $breakpoint) {
        $options[$breakpoint->machine_name] = $breakpoint->breakpoint;
      }
    }

    // Add the media selector field
    $element['media'] = array(
      '#type' => 'select',
      '#options' => $options,
      '#title' => t('Media query'),
      '#description' => t('Select what media (all, print, screen...) or breakpoint this css should be applied to.'),
      '#default_value' => isset($item['media']) ? $item['media'] : $defaults['media'],
    );
    if (!empty($instance['settings']['description_field'])) {

      // Add the description field if enabled.
      $element['description'] = array(
        '#type' => 'textfield',
        '#title' => t('Description'),
        '#value' => isset($item['description']) ? $item['description'] : '',
        '#maxlength' => 255,
        '#description' => t('The description may be used as the label of the link to the file.'),
      );
    }
  }

  // Adjust the Ajax settings so that on upload and remove of any individual
  // file, the entire group of file fields is updated together.
  if ($field['cardinality'] != 1) {
    $parents = array_slice($element['#array_parents'], 0, -1);
    $new_path = 'file/ajax/' . implode('/', $parents) . '/' . $form['form_build_id']['#value'];
    $field_element = drupal_array_get_nested_value($form, $parents);
    $new_wrapper = $field_element['#id'] . '-ajax-wrapper';
    foreach (element_children($element) as $key) {
      if (isset($element[$key]['#ajax'])) {
        $element[$key]['#ajax']['path'] = $new_path;
        $element[$key]['#ajax']['wrapper'] = $new_wrapper;
      }
    }
    unset($element['#prefix'], $element['#suffix']);
  }

  // Add another submit handler to the upload and remove buttons, to implement
  // functionality needed by the field widget. This submit handler, along with
  // the rebuild logic in file_field_widget_form() requires the entire field,
  // not just the individual item, to be valid.
  foreach (array('upload_button', 'remove_button') as $key) {
    $element[$key]['#submit'][] = 'css_field_field_widget_submit';
    $element[$key]['#limit_validation_errors'] = array(array_slice($element['#parents'], 0, -1));
  }

  return $element;
}

/**
 * An element #process callback for a group of css_file fields.
 *
 * Adds the weight field to each row so it can be ordered and adds a new Ajax
 * wrapper around the entire group so it can be replaced all at once.
 */
function css_field_field_widget_process_multiple($element, &$form_state, $form) {
  return file_field_widget_process_multiple($element, $form_state, $form);
}

/**
 * Form submission handler for upload/remove button of css_field_field_widget_form().
 *
 * This runs in addition to and after file_managed_file_submit().
 *
 * @see file_managed_file_submit()
 * @see file_field_widget_form()
 * @see file_field_widget_process()
 */
function css_field_field_widget_submit($form, &$form_state) {
  file_field_widget_submit($form, $form_state);
}

/**
 * Implementation of hook_field_is_empty().
 */
function css_field_field_is_empty($item, $field) {

  switch($field['type']) {
    case 'css_field':
      return empty($item['css']);
    case 'css_file':
      return empty($item['fid']);
  }

  return FALSE;
}

/**
 * Implements hook_field_validate().
 */
function css_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  $type = $field['type'];
  $widget = $instance['widget'];
  $settings = $widget['settings'];
  global $language;
  $unable_to_connect = FALSE;

  // External validation is only for css_field at the moment.
  // @TODO provide external validation for css_file widget.
  if ($type == 'css_field') {
    // For each item, try to send it to the validator
    foreach ($items as $delta => $item) {

      if (!empty($item['css'])) {
        // If external validation is turned on and its the text area widget.
        if ($settings['css_field_enable_online_validation'] == TRUE) {
          // Assemble our validation email that will go to w3.org.
          $url = 'http://jigsaw.w3.org/css-validator/validator?profile=css3&output=text&lang=' . $language->language . '&text=' . urlencode($item['css']);
          $response = drupal_http_request($url);
          if ($response->code == 200) {
            $error = strpos($response->data, 'Sorry!');
            if ($error !== FALSE) {
              $errors[$field['field_name']][$langcode][$delta][] = array(
                'error' => 'css_syntax',
                'message' => $response->data,
              );
            }
          }
          // If we couldn't connect to the service, allow the code for now.
          elseif ($response->code != 200) {
            $unable_to_connect = TRUE;
          }
        }
      }

    }
    if ($unable_to_connect == TRUE) {
      drupal_set_message(t('Could not connect to W3Validator to perform css validation on all or some of your css snippets. Your code has been allowed...for now.'), 'warning');
    }
  }
}

/**
 * Implements hook_field_formatter_info().
 */
function css_field_field_formatter_info() {
  return array(
    // CSS Field formatters information.
    'css_field' => array(
      'label' => t('CSS: Functioning'),
      'field types' => array('css_field'),
      'settings' => array(
        'css_field_debug_message' => TRUE,
      ),
    ),
    'css_field_plain' => array(
      'label' => t('CSS: Plain'),
      'field types' => array('css_field'),
    ),
    'css_field_styled' => array(
      'label' => t('CSS: Styled'),
      'field types' => array('css_field'),
      'settings' => array(
        'css_field_display_theme' => 'solarized_dark',
      ),
    ),
    // CSS File formatters information.
    'css_file' => array(
      'label' => t('CSS File : Functioning'),
      'field types' => array('css_file'),
      'settings' => array(
        'css_field_debug_message' => TRUE,
      ),
    ),
    'css_file_url' => array(
      'label' => t('CSS File : File URL'),
      'field types' => array('css_file'),
    ),
    'css_file_link' => array(
      'label' => t('CSS File : Link to file'),
      'field types' => array('css_file'),
    ),
    'css_file_plain' => array(
      'label' => t('CSS File : Plain'),
      'field types' => array('css_file'),
    ),
    'css_file_styled' => array(
      'label' => t('CSS File : Styled'),
      'field types' => array('css_file'),
      'settings' => array(
        'css_field_display_theme' => 'solarized_dark',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function css_field_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  switch ($display['type']) {
    case 'css_field_styled':
    case 'css_file_styled':
      // Set up our select list of applicable editor themes.
      $element['css_field_display_theme'] = array(
        '#type' => 'select',
        '#options' => _css_field_list_of_editor_themes(),
        '#title' => t('Select display theme'),
        '#description' => t("Select the theme style for the display of this css field"),
        '#default_value' => isset($settings['css_field_display_theme']) ? $settings['css_field_display_theme'] : 'solarized_dark',
      );
      break;

    case 'css_field':
    case 'css_file':
      // Set up our checkbox to enable/disable css field debugging.
      $element['css_field_debug_message'] = array(
        '#type' => 'checkbox',
        '#title' => t('Display dev/debug message'),
        '#description' => t("This will display a message notifying users that this page has additional css coming from a css field.  Users must have permission to view dev/debug messages. "),
        '#default_value' => isset($settings['css_field_debug_message']) ? $settings['css_field_debug_message'] : TRUE,
      );
      break;
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function css_field_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $summary = '';

  switch ($display['type']) {
    case 'css_field_styled':
    case 'css_file_styled':
      // Summary of our styled editor theme.
      $summary = t('Display theme: @theme', array('@theme' => $settings['css_field_display_theme']));
      break;

    case 'css_field':
    case 'css_file':
      // Summary of our debug status.
      $status = $settings['css_field_debug_message'] == TRUE ? t('Enabled') : t('Disabled');
      $summary = t('Debug message: @status', array('@status' => $status));
      break;
  }

  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function css_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, &$items, $display) {
  $settings = $display['settings'];
  $element = array();

  switch ($display['type']) {
    case 'css_file':
    case 'css_field':
      // Auto kill the embedded css display if entity is being viewed
      // from an admin page. This is to try to preserve sanity. If this field is
      // needed to work for admin display, than realistically you need to
      // rethink what you are doing. :) Discovered on views admin pages that if
      // looking at rendered types with functioning css formatter, it was
      // rendering that css.
      $page_is_admin = path_is_admin(current_path());
      if (!$page_is_admin) {
        //
        // Display debug messaging if enabled and to users with permission.
        // We want dev's to have an easy time figuring out where the odd css
        // may be coming from.
        if (!empty($items) && ($settings['css_field_debug_message'] == TRUE) && user_access('view css field debug')) {
          $debug_message = _css_field_generate_css_comment($entity_type, $entity, $field, $instance, $langcode, $display);
          drupal_set_message($debug_message);
        }

        foreach ($items as $delta => $item) {
          //
          // If breakpoint module is enabled, get the breakpoint info from the
          // name. if no breakpoint is returned, then use the original value
          // from the field
          $breakpoint = NULL;
          if (module_exists('breakpoints')) {
            $breakpoint = breakpoints_breakpoint_load_by_fullkey($item['media']);
          }
          $media = !empty($breakpoint) ? $breakpoint->breakpoint : $item['media'];

          // Set the data as the css content.
          $content = _css_field_get_content($item, $entity_type, $field, $instance);
          $data = filter_xss($content);
          // Set up the basic options. We use inline css for 2 reasons.
          // 1) So that both snippet and file functioning css are output
          // in the same manner.
          // 2) We can run the content through more strict filtering and do
          // our best to keep the content as secure as possible.
          $options = array(
            'type' => 'inline',
            'basename' => 'css_field_' . $entity_type,
            'media' => $media,
            'group' => CSS_THEME,
            'preprocess' => TRUE,
            'weight' => '9999',
            'attributes' => array(
              'class' => 'css-field',
            ),
          );
          drupal_add_css($data, $options);
        }
      }
      break;
    case 'css_file_plain':
    case 'css_field_plain':
      foreach ($items as $delta => $item) {
        $content = _css_field_get_content($item, $entity_type, $field, $instance);
        $element[$delta] = array(
          '#type' => 'markup',
          '#prefix' => '<pre>',
          '#markup' => filter_xss($content),
          '#suffix' => '</pre>',
        );
      }
      break;
    case 'css_file_styled':
    case 'css_field_styled':
      $display_theme = $settings['css_field_display_theme'];
      if ($display_theme != 'none') {
        drupal_add_js('//cdn.jsdelivr.net/ace/1.2.3/noconflict/ace.js', array('type' => 'external', 'scope' => 'header', 'group' => JS_THEME, 'every_page' => TRUE, 'weight' => -1,));
        drupal_add_js(drupal_get_path('module', 'css_field') . '/js/css_field.js');
        foreach ($items as $delta => $item) {
          $content = _css_field_get_content($item, $entity_type, $field, $instance);
          $element[$delta] = array(
            '#type' => 'textarea',
            '#value' => filter_xss($content),
            '#row' => 10,
            '#attributes' => array(
              'data-ace-editor-css-readonly' => 'data-ace-editor-css-readonly',
              'data-ace-editor-css-theme' => $display_theme,
            ),
          );
        }
      }
      else {
        foreach ($items as $delta => $item) {
          $content = _css_field_get_content($item, $entity_type, $field, $instance);
          $element[$delta] = array(
            '#type' => 'markup',
            '#prefix' => '<pre>',
            '#value' => filter_xss($content),
            '#suffix' => '</pre>',
          );
        }
      }
      break;

    case 'css_file_url':
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => empty($item['uri']) ? '' : file_create_url($item['uri']));
      }
      break;

    case 'css_file_link':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#theme' => 'file_link',
          '#file' => (object) $item,
        );
      }
      break;
  }

  return $element;
}

/**
 * Helper function to get content for the css field. Checks if its a file or
 * snippet field
 *
 * @param $item
 *        array: data and value of the individual field item.
 * @param $entity_type
 *        string: The type of entity
 * @param $field
 *        array: data about the field
 * @param $instance
 *        array: data about the field instance
 *
 * @return string
 */
function _css_field_get_content($item, $entity_type, $field, $instance) {
  // If its the css_file field, the uri will be set. If its a file, we
  // retrieve the contents of that file, so we can return it as inline
  // css.
  $content = '';

  if (isset($item['uri'])) {
    if (is_file($item['uri'])) {
      $content = file_get_contents($item['uri']);
    }
    else {
      $missing_file = _css_field_generate_missing_file_message($item, $entity_type, $field, $instance);
      drupal_set_message($missing_file, 'warning');
    }
  }
  elseif (isset($item['css'])) {
    $content = $item['css'];
  }

  return $content;
}

/**
 * Helper function to generate the CSS comment
 *
 * This comment will help users identify where the css is coming from and make
 * it easier to debug when its embedded.
 *
 * @param $entity_type
 *        string: The type of entity
 * @param $entity
 *        array: data about the entity
 * @param $field
 *        array: data about the field
 * @param $instance
 *        array: data about the field instance
 * @param $langcode
 *        string: language of the current state
 * @param $display
 *        array: data about the view mode of the entity
 *
 * @return string
 */
function _css_field_generate_css_comment($entity_type, $entity, $field, $instance, $langcode, $display) {
  $info = entity_get_info($entity_type);
  $uri = entity_uri($entity_type, $entity);

  $css_comment = NULL;
  $css_comment .= t('This page has additional css coming from the @entity_label field named "@field_label" (@field_name). ' , array('@field_name' => $field['field_name'], '@field_label' => $instance['label'], '@entity_label' => $info['label']));
  $css_comment .= t("Visit !url to edit this code." , array('!url' => l($uri['path'] . '/edit', $uri['path'] . '/edit', array())));

  return $css_comment;
}

/**
 * Helper function to generate the CSS missing file message
 *
 * This comment will help users identify where the css is coming from and make
 * it easier to debug when its embedded.
 *
 * @param $entity_type
 *        string: The type of entity
 * @param $field
 *        array: data about the field
 * @param $instance
 *        array: data about the field instance
 *
 * @return string
 */
function _css_field_generate_missing_file_message($item, $entity_type, $field, $instance) {
  $info = entity_get_info($entity_type);
  $css_missing_message = t('This page should have additional css coming from field "@field_label" (@field_name), but @uri cannot be found.' , array('@field_name' => $field['field_name'], '@field_label' => $instance['label'], '@entity_label' => $info['label'], '@uri' => $item['uri']));

  return $css_missing_message;
}

/**
 * Helper function to get list of available ace editor themes
 *
 * Use hook_css_field_list_of_editor_themes_alter() and add new themes to the
 * options. Visit https://github.com/ajaxorg/ace/tree/master/lib/ace/theme to
 * see the full list of available themes from ace.
 *
 * @return array
 */
function _css_field_list_of_editor_themes() {
  $options = array(
    'none' => t('None'),
    'solarized_dark' => t('Solarized Dark'),
    'solarized' => t('Solarized'),
    'ambiance' => t('Ambiance'),
    'dreamweaver' => t('Dreamweaver'),
    'monokai' => t('Monokai'),
  );

  drupal_alter('css_field_list_of_editor_themes', $options);

  return $options;
}

/**
 * Implements hook_field_load().
 */
function css_field_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age) {
  if ($field['type'] == 'css_file') {
    file_field_load($entity_type, $entities, $field, $instances, $langcode, $items, $age);
  }
}

/**
 * Implements hook_field_prepare_view().
 */
function css_field_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items) {
  if ($field['type'] == 'css_file') {
    file_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, $items);
  }
}

/**
 * Implements hook_field_presave().
 */
function css_field_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'css_file') {
    file_field_presave($entity_type, $entity, $field, $instance, $langcode, $items);
  }
}

/**
 * Implements hook_field_insert().
 */
function css_field_field_insert($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'css_file') {
    file_field_insert($entity_type, $entity, $field, $instance, $langcode, $items);
  }
}

/**
 * Implements hook_field_update().
 */
function css_field_field_update($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'css_file') {
    file_field_update($entity_type, $entity, $field, $instance, $langcode, $items);
  }
}

/**
 * Implements hook_field_delete().
 */
function css_field_field_delete($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'css_file') {
    file_field_delete($entity_type, $entity, $field, $instance, $langcode, $items);
  }
}

/**
 * Implements hook_field_delete_revision().
 */
function css_field_field_delete_revision($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'css_file') {
    file_field_delete_revision($entity_type, $entity, $field, $instance, $langcode, $items);
  }
}
